import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Brockleby's Pies",
    slug: "brockleby-s-pies",
    bio: "Award-winning farmers and pie makers from Melton Mowbray, handcrafting pies with 48 British Pie Awards to prove it.",
    story: "We've been farming and baking in Melton Mowbray for decades — a town that quite literally put the pork pie on the map. For us, making pies isn't just a trade; it's a way of honouring where we come from and the incredible ingredients this landscape produces. Every pie we shape by hand carries that sense of place — the uncured pork, the hot-water crust, the care that goes into every crimp and fold. We're proud to hold 48 British Pie Awards, but what really drives us is the moment someone takes that first bite and knows they're eating something genuinely made with love.",
    location: "Melton Mowbray, Leicestershire",
    address: {
      line1: "Brocklebys Farm",
      city: "Melton Mowbray",
      county: "Leicestershire",
      postcode: "LE14",
      country: "GB",
    },
    categories: ["Pies","Artisan Baked Goods"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/hero.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@brocklebys",
      facebook: "brocklebys",
    },
    rating: 4.8,
    reviewCount: 124,
    createdAt: new Date("1995-01-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Authentic Melton Mowbray Pork Pie",
    description: "The original and the finest — a traditionally made Melton Mowbray Pork Pie built on a hand-raised hot-water pastry crust, filled with coarsely chopped, uncured British pork seasoned with a whisper of pepper and sage. Baked until the pastry is a deep, burnished gold, then finished with a slow pour of savoury jelly that sets overnight. This is PGI-protected craftsmanship in every bite.",
    slug: "authentic-melton-mowbray-pork-pie",
    category: "Pies",
    price: 695,
    unit: "individual pie (serves 1–2)",
    stock: 50,
    images: ["/images/authentic-melton-mowbray-pork-pie.jpg"],
    dietary: [],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Moo & Blue — Steak & Stilton Pie",
    description: "A Supreme Champion at the British Pie Awards, and one taste tells you exactly why. Slow-braised British beef steak is folded through a rich, deeply savoury gravy, then crowned with crumbles of tangy Stilton that melt into the filling during baking. Encased in a golden shortcrust lid with a buttery, flaky finish — this is the pie that wins rooms over.",
    slug: "moo-blue-steak-stilton-pie",
    category: "Pies",
    price: 850,
    unit: "individual pie (serves 1–2)",
    stock: 50,
    images: ["/images/moo-blue-steak-stilton-pie.jpg"],
    dietary: [],
    allergens: ["gluten","dairy"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Wild Venison Pie",
    description: "Inspired by the wild landscapes of the British countryside, this pie is packed with lean, tender venison slow-cooked in a dark ale gravy with juniper and thyme until the meat practically melts. Beneath a crisp, bronzed pastry lid, the filling is earthy, warming, and unmistakably game — bold enough to be extraordinary, refined enough to be elegant.",
    slug: "wild-venison-pie",
    category: "Pies",
    price: 895,
    unit: "individual pie (serves 1–2)",
    stock: 50,
    images: ["/images/wild-venison-pie.jpg"],
    dietary: [],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Gluten-Free Selection Pack",
    description: "Four handmade pies crafted without compromise — every bit as buttery, generously filled, and satisfying as their classic counterparts. The gluten-free pastry is short and golden, shattering beautifully to reveal hearty fillings made to the same award-winning standards. A brilliant gift or a treat for anyone who knows great pie shouldn't be off limits.",
    slug: "gluten-free-selection-pack",
    category: "Gifts & Bundles",
    price: 2995,
    unit: "box of 4 individual pies",
    stock: 50,
    images: ["/images/gluten-free-selection-pack.jpg"],
    dietary: ["gluten-free"],
    allergens: ["eggs"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Trio of Champions Gift Box",
    description: "Three of Brockleby's most celebrated award-winning pies presented together in a handsome gift box — the ultimate way to share the love of great British pie. Each pie in the trio has claimed glory at the British Pie Awards, making this a collection of genuine champions. Whether it's a birthday, a thank-you, or simply because someone deserves something special, this box delivers.",
    slug: "trio-of-champions-gift-box",
    category: "Gifts & Bundles",
    price: 2495,
    unit: "gift box of 3 pies",
    stock: 50,
    images: ["/images/trio-of-champions-gift-box.jpg"],
    dietary: [],
    allergens: ["gluten","dairy","eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Mary Cherry Pie",
    description: "A luscious, deep-filled sweet pie bursting with plump, sweet-tart British cherries in a rich, glossy fruit filling — the kind that bubbles up beneath the pastry lid and stains it a gorgeous ruby red. The shortcrust pastry is delicate and crumbly, dusted with a little caster sugar that caramelises faintly in the oven. Serve warm with clotted cream and the world is a better place.",
    slug: "mary-cherry-pie",
    category: "Sweet Pies",
    price: 750,
    unit: "individual dessert pie (serves 2)",
    stock: 50,
    images: ["/images/mary-cherry-pie.jpg"],
    dietary: ["vegetarian"],
    allergens: ["gluten","dairy","eggs"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Isaac's Apple Pie",
    description: "A proper old-fashioned apple pie — generously filled with thick slices of British Bramley apple, fragrant with cinnamon and a squeeze of lemon, all cushioned inside a melt-in-the-mouth butter pastry. The lid is crimped by hand and glazed to a warm, amber shine. It's the kind of pie that fills the kitchen with the most irresistible smell and tastes exactly like it should.",
    slug: "isaac-s-apple-pie",
    category: "Sweet Pies",
    price: 750,
    unit: "individual dessert pie (serves 2)",
    stock: 50,
    images: ["/images/isaac-s-apple-pie.jpg"],
    dietary: ["vegetarian"],
    allergens: ["gluten","dairy","eggs"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Father's Day Pie Gift Hamper",
    description: "The perfect gift for the pie-lover in your life — a curated hamper of Brockleby's finest, including a classic Melton Mowbray Pork Pie, a hearty savoury pie of the season, and a sweet pie to finish. Presented in seasonal gift packaging with a personalised card option, it's the kind of thoughtful present that says you actually know them. Delivered fresh and ready to enjoy.",
    slug: "father-s-day-pie-gift-hamper",
    category: "Gifts & Bundles",
    price: 3495,
    unit: "gift hamper (3 pies + packaging)",
    stock: 50,
    images: ["/images/father-s-day-pie-gift-hamper.jpg"],
    dietary: [],
    allergens: ["gluten","dairy","eggs"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Sarah M.",
    producerId: "producer-1",
    rating: 5,
    comment: "Absolutely outstanding. Authentic Melton Mowbray Pork Pie was everything the description promised and more. Beautifully packaged, arrived perfectly fresh. Already placed my second order.",
    createdAt: new Date("2024-04-07"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "James T.",
    producerId: "producer-1",
    rating: 5,
    comment: "Sent a selection as a gift and got a phone call from my parents saying it was the best thing they'd ever received. Quality you simply cannot find in a supermarket. Will be ordering monthly.",
    createdAt: new Date("2024-04-21"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Rachel H.",
    producerId: "producer-1",
    rating: 5,
    comment: "I've been ordering from Brockleby's Pies for six months now and the quality has never dipped once. Proper craft food made by people who genuinely care. Nothing else comes close.",
    createdAt: new Date("2024-05-04"),
  },
];

export const MOCK_ORDERS: Order[] = [];
