import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "The Pie Merchant",
    slug: "the-pie-merchant",
    bio: "Hand-crimped pies, pasties, and sausage rolls made from scratch in our Shrewsbury bakery since 1987. All-butter shortcrust, slow-braised fillings, and nothing from a tin or a packet.",
    story:
      "My mother started selling pies at Shrewsbury market in 1987 with a borrowed trestle table and twelve steak and kidney pies. She sold out before 10am. By 1990 she had a bakery on Pride Hill and a waiting list for Christmas orders. I took over in 2009 and we've barely changed a thing — same recipes, same suppliers, same hand-crimping technique she developed in that first kitchen. We use Shropshire beef from a farm three miles away, free-range pork from a small producer near Ludlow, and root vegetables from our kitchen garden. Every pie is made to order — we don't bake for stock. The pastry is all-butter shortcrust, made fresh every morning. The fillings are slow-braised overnight — the steak and ale goes in the oven at 8pm and comes out at 6am. It's not efficient, but it's the only way to get the depth of flavour we want. We deliver across the UK in chilled packaging every Tuesday and Friday.",
    location: "Pride Hill, Shrewsbury",
    address: {
      line1: "24 Pride Hill",
      city: "Shrewsbury",
      county: "Shropshire",
      postcode: "SY1 1DQ",
      country: "GB",
    },
    categories: ["pies", "pastry"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/pork-pie.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@thepiemerchant",
      facebook: "ThePieMerchant",
    },
    rating: 4.9,
    reviewCount: 742,
    createdAt: new Date("1987-11-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "The Pie Merchant",
    producerSlug: "the-pie-merchant",
    name: "Shropshire Steak & Ale Pie",
    description:
      "Our original and most celebrated pie. Shropshire beef braised overnight in Hobsons Best Bitter with carrots, shallots, and a bouquet garni, piled into a hand-crimped all-butter shortcrust case. Serves one generously. Ready to bake from chilled in 35 minutes.",
    slug: "shropshire-steak-ale-pie",
    category: "pies",
    price: 650,
    unit: "individual pie (serves 1)",
    stock: 100,
    images: [
      "https://images.unsplash.com/photo-1562440499-64c9a111f713?w=800&q=80",
    ],
    dietary: [],
    allergens: ["gluten", "dairy"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "The Pie Merchant",
    producerSlug: "the-pie-merchant",
    name: "Chicken, Leek & Tarragon Pie",
    description:
      "Free-range chicken thighs slow-poached with leeks, celery, and fresh tarragon in a cream and white wine sauce. A lighter, more elegant pie than our steak — but no less satisfying. All-butter shortcrust top and bottom, hand-crimped edge.",
    slug: "chicken-leek-tarragon-pie",
    category: "pies",
    price: 600,
    unit: "individual pie (serves 1)",
    stock: 80,
    images: [
      "https://images.unsplash.com/photo-1513442542250-854d436a73f2?w=800&q=80",
    ],
    dietary: [],
    allergens: ["gluten", "dairy"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "The Pie Merchant",
    producerSlug: "the-pie-merchant",
    name: "Classic Pork Pie (400g)",
    description:
      "A hand-raised hot water crust pork pie using free-range Shropshire pork with a traditional blend of white pepper, mace, and fresh sage. Baked in our Victorian pie moulds, with a set jelly poured in while still warm. Best eaten at room temperature with good mustard.",
    slug: "classic-pork-pie-400g",
    category: "pies",
    price: 850,
    unit: "400g whole pie",
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1562440499-64c9a111f713?w=800&q=80",
    ],
    dietary: [],
    allergens: ["gluten", "dairy"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "The Pie Merchant",
    producerSlug: "the-pie-merchant",
    name: "Slow-Braised Lamb & Rosemary Pie",
    description:
      "Herdwick lamb shoulder braised for six hours with rosemary, red wine, and root vegetables until it falls apart. Deeply savoury, intensely flavoured. This is the pie that sells out first every week. Available Friday and Saturday only.",
    slug: "slow-braised-lamb-rosemary-pie",
    category: "pies",
    price: 700,
    unit: "individual pie (serves 1)",
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1513442542250-854d436a73f2?w=800&q=80",
    ],
    dietary: [],
    allergens: ["gluten", "dairy"],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "The Pie Merchant",
    producerSlug: "the-pie-merchant",
    name: "Pork & Black Pudding Sausage Roll",
    description:
      "Coarsely minced Shropshire pork with crumbled Bury black pudding, fresh thyme, and a crack of black pepper, wrapped in rough-puff pastry and baked until deeply golden. One large sausage roll per portion. Proper food.",
    slug: "pork-black-pudding-sausage-roll",
    category: "pastry",
    price: 350,
    unit: "1 large sausage roll",
    stock: 120,
    images: [
      "https://images.unsplash.com/photo-1562440499-64c9a111f713?w=800&q=80",
    ],
    dietary: [],
    allergens: ["gluten", "dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "The Pie Merchant",
    producerSlug: "the-pie-merchant",
    name: "Family Steak Pie (serves 4)",
    description:
      "Our steak and ale filling in a large oval pie dish, lidded with all-butter shortcrust and sent to you ready to bake. The simplest, most satisfying Sunday dinner we know. Feeds four adults comfortably with mash and greens.",
    slug: "family-steak-pie",
    category: "pies",
    price: 2200,
    unit: "large oval pie (serves 4)",
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1513442542250-854d436a73f2?w=800&q=80",
    ],
    dietary: [],
    allergens: ["gluten", "dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "The Pie Merchant",
    producerSlug: "the-pie-merchant",
    name: "Cornish Pasty",
    description:
      "Skirt beef, swede, potato, and onion — seasoned simply with salt and pepper, crimped by hand on top in the traditional Cornish style. We make these every Wednesday. They're not Cornish but they're made the right way and we're proud of them.",
    slug: "cornish-pasty",
    category: "pastry",
    price: 400,
    unit: "1 large pasty",
    stock: 80,
    images: [
      "/images/cornish-pasty.jpg",
    ],
    dietary: [],
    allergens: ["gluten", "dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "The Pie Merchant",
    producerSlug: "the-pie-merchant",
    name: "Pie Selection Box (4 pies)",
    description:
      "One each of our four bestsellers — Steak & Ale, Chicken & Leek, Lamb & Rosemary, and our Vegetable Wellington. A complete introduction to what we do, in a gift-ready kraft box. Perfect for sending to someone who deserves a proper meal.",
    slug: "pie-selection-box-4",
    category: "pies",
    price: 2400,
    unit: "4 individual pies",
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1513442542250-854d436a73f2?w=800&q=80",
    ],
    dietary: [],
    allergens: ["gluten", "dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-03-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Mike F.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The steak and ale pie is simply the best pie I've ever eaten. The pastry is extraordinary — buttery, short, deeply flavoured — and the filling has a depth you only get from a genuinely long braise. I order two a week now. Genuinely life-changing.",
    createdAt: new Date("2024-04-07"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "Karen B.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "Sent the family pie box to my parents for their anniversary and they rang me in tears of joy. My dad said it was the best pie he'd eaten since his mother used to make them in the 1960s. High praise. Will be ordering monthly.",
    createdAt: new Date("2024-04-21"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Steve O.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The pork pie converted me. I'd given up on pork pies after years of supermarket disappointment — dense, bland, surrounded by that horrible gel. This one has proper jelly, a fragrant filling, and a crust with actual flavour. Ordered three more immediately.",
    createdAt: new Date("2024-05-04"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo Customer",
    items: [
      {
        productId: "prod-1",
        productName: "Shropshire Steak & Ale Pie",
        producerId: "producer-1",
        producerName: "The Pie Merchant",
        price: 650,
        quantity: 4,
        unit: "individual pie",
        imageUrl: "/images/hero.jpg",
      },
      {
        productId: "prod-5",
        productName: "Pork & Black Pudding Sausage Roll",
        producerId: "producer-1",
        producerName: "The Pie Merchant",
        price: 350,
        quantity: 4,
        unit: "1 large sausage roll",
        imageUrl: "/images/hero.jpg",
      },
    ],
    producerIds: ["producer-1"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "7 The Square",
      city: "Shrewsbury",
      postcode: "SY1 1LA",
      country: "GB",
    },
    subtotal: 4000,
    commission: 0,
    deliveryFee: 395,
    total: 4395,
    stripePaymentIntentId: "pi_demo_pies_001",
    createdAt: new Date("2024-04-11"),
    updatedAt: new Date("2024-04-12"),
  },
];
