import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Brockleby's Pies",
    slug: "brockleby-s-pies",
    bio: "Award-winning pie makers and farmers from Melton Mowbray, crafting hand-raised artisan pies since the 1990s.",
    story: "We're farmers at heart — and that means we know exactly where our meat comes from before it ever meets pastry. Growing up in Leicestershire, making pies wasn't just a trade, it was a way of honouring the land and the traditions of Melton Mowbray that stretch back centuries. We hand-raise every pork pie the traditional way: hot water crust pastry moulded by hand, packed with seasoned free-range pork, and finished with our signature jellied stock. Winning 48 British Pie Awards — including Supreme Champion — means the world to us, but honestly, nothing beats hearing that someone finished the last crumb.",
    location: "Melton Mowbray, Leicestershire",
    address: {
      line1: "Brocklebys Farm",
      city: "Melton Mowbray",
      county: "Leicestershire",
      postcode: "LE14 3PX",
      country: "GB",
    },
    categories: ["Pies","Savoury Pastry","Sweet Pies","Gift Food"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/hero.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@brocklebys",
      facebook: "BrocklebysPies",
    },
    rating: 4.8,
    reviewCount: 124,
    createdAt: new Date("1990-01-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Original Melton Mowbray Pork Pie",
    description: "The one that started it all. Our hand-raised pork pie is made the authentic Melton Mowbray way — uncured, coarsely chopped free-range pork seasoned with black pepper and anchovy, packed into a golden hot water crust pastry and finished with savoury jellied stock. Earthy, satisfying, and utterly unmistakeable.",
    slug: "original-melton-mowbray-pork-pie",
    category: "Pies",
    price: 595,
    unit: "individual pie (serves 1–2)",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1600628421066-f6b77a2e9f0a?w=800&q=80"],
    dietary: [],
    allergens: ["gluten","eggs","fish"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Moo & Blue — Steak & Stilton Pie",
    description: "Our Supreme Champion award-winner and arguably the finest pie we've ever made. Slow-braised British beef shin falls apart in a rich, dark gravy, lifted by crumbles of pungent Cropwell Bishop Stilton — the whole thing encased in a deeply bronzed, buttery shortcrust. Each bite delivers layers of umami depth that linger long after the plate is cleared.",
    slug: "moo-blue-steak-stilton-pie",
    category: "Pies",
    price: 750,
    unit: "individual pie (serves 1–2)",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80"],
    dietary: [],
    allergens: ["gluten","dairy","eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Chicken, Leek & Smoked Bacon Pie",
    description: "Free-range British chicken thighs, slow-cooked until tender and entwined with sweet braised leeks and smoky dry-cured bacon in a velvet cream sauce. Topped with a flaky puff pastry lid that shatters at the fork, this is a proper comfort pie — the kind you come back to on grey afternoons.",
    slug: "chicken-leek-smoked-bacon-pie",
    category: "Pies",
    price: 725,
    unit: "individual pie (serves 1–2)",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1608855238293-a8853e7f7c98?w=800&q=80"],
    dietary: [],
    allergens: ["gluten","dairy","eggs","celery"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Scrumpers Bramley Apple & Blackberry Pie",
    description: "Sharp, fragrant Bramley apples from the Vale of Belvoir meet plump wild blackberries in a lightly spiced filling that bubbles and perfumes as it bakes. Nestled in a crumbly, golden shortcrust dusted with caster sugar, this dessert pie is best served warm with a slick of clotted cream — though we won't judge if you eat it cold over the sink.",
    slug: "scrumpers-bramley-apple-blackberry-pie",
    category: "Sweet Pies",
    price: 650,
    unit: "individual pie (serves 2)",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=800&q=80"],
    dietary: ["vegetarian"],
    allergens: ["gluten","dairy","eggs"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Gluten-Free Steak & Ale Pie",
    description: "Nobody should miss out on a great pie. We've crafted this gluten-free shortcrust from scratch — not an afterthought, but a recipe we're genuinely proud of — filled with tender chunks of British beef braised in a malty local ale with sweet caramelised onions and woody thyme. Rich, deeply flavoured, and made without compromise.",
    slug: "gluten-free-steak-ale-pie",
    category: "Pies",
    price: 795,
    unit: "individual pie (serves 1–2)",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80"],
    dietary: ["gluten-free"],
    allergens: ["eggs","dairy","celery"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Vegetarian Roasted Root & Brie Pie",
    description: "Sweet honey-roasted parsnips, carrots and butternut squash are tossed with caramelised red onion and topped with generous slices of creamy, bloomy Brie before being sealed beneath a bronzed shortcrust lid. This is vegetarian baking done with full conviction — warming, satisfying, and absolutely worthy of the dinner table.",
    slug: "vegetarian-roasted-root-brie-pie",
    category: "Pies",
    price: 725,
    unit: "individual pie (serves 1–2)",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80"],
    dietary: ["vegetarian"],
    allergens: ["gluten","dairy","eggs"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Award-Winners Pie Bundle — Six-Pie Hamper",
    description: "Six of our most celebrated pies, hand-picked from the award shelf and packed in a gift-ready Brockleby's box with a tasting card. Includes the Supreme Champion Moo & Blue, the Original Melton Mowbray Pork Pie, and four seasonal favourites — a brilliant introduction to the full range, and an even better gift for someone who deserves the best.",
    slug: "award-winners-pie-bundle-six-pie-hamper",
    category: "Gift Food",
    price: 3895,
    unit: "gift hamper (6 pies, serves 6–8)",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80"],
    dietary: [],
    allergens: ["gluten","dairy","eggs","fish","celery"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "Brockleby's Pies",
    producerSlug: "brockleby-s-pies",
    name: "Mary Cherry — Morello Cherry & Almond Pie",
    description: "Plump, tart Morello cherries swim in a lightly sweetened kirsch syrup alongside toasted flaked almonds and a whisper of vanilla, all cradled in a crisp, buttery pastry case with a lattice top that caramelises beautifully in the oven. Named with affection, baked with care — this is the sweet pie that converts savoury-only pie sceptics.",
    slug: "mary-cherry-morello-cherry-almond-pie",
    category: "Sweet Pies",
    price: 650,
    unit: "individual pie (serves 2)",
    stock: 50,
    images: ["https://images.unsplash.com/photo-1562007908-17c67e878c88?w=800&q=80"],
    dietary: ["vegetarian"],
    allergens: ["gluten","dairy","eggs","nuts"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Sarah M.",
    producerId: "producer-1",
    rating: 5,
    comment: "Absolutely outstanding. Original Melton Mowbray Pork Pie was everything the description promised and more. Beautifully packaged, arrived perfectly fresh. Already placed my second order.",
    createdAt: new Date("2024-04-07"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "James T.",
    producerId: "producer-1",
    rating: 5,
    comment: "Sent a selection as a gift and got a phone call from my parents saying it was the best thing they'd ever received. Quality you simply cannot find in a supermarket. Will be ordering monthly.",
    createdAt: new Date("2024-04-21"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Rachel H.",
    producerId: "producer-1",
    rating: 5,
    comment: "I've been ordering from Brockleby's Pies for six months now and the quality has never dipped once. Proper craft food made by people who genuinely care. Nothing else comes close.",
    createdAt: new Date("2024-05-04"),
  },
];

export const MOCK_ORDERS: Order[] = [];
